version: "3.9"

services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
    - 5432:5432

  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: >
      bash -c "python run.py"
    volumes:
      - .:/app
    depends_on:
      - db