version: "3.9"

services:
  db:
    image: postgres:14
    env_file:
      - env/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
    - 5432:5432

  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/.env
    command: >
      bash -c "python run.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db