"""empty message

Revision ID: 076b5298863f
Revises: 608a4b67f99e
Create Date: 2023-01-21 19:35:33.442426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076b5298863f'
down_revision = '608a4b67f99e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column(
        'bonus_crafting_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'bonus_crafting_time')
    # ### end Alembic commands ###
