"""initial

Revision ID: 608a4b67f99e
Revises:
Create Date: 2023-01-21 19:18:25.306905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '608a4b67f99e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
                    sa.Column('uid', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('item_type', postgresql.ENUM('ws', 'wa', 'wd', 'wm', 'wp', 'wb', 'wt', 'ww', 'wg', 'wc', 'ah', 'am', 'al', 'hh', 'hm', 'hl', 'gh', 'gl',
                                                           'bh', 'bl', 'uh', 'up', 'us', 'xs', 'xr', 'xa', 'xc', 'xf', 'fm', 'fd', 'z', 'm', 'xu', 'xm', name='itemtype'), autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('tier', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('image', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('base_gold_value', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('merchant_exp', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('worker_exp', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('worker1', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('worker2', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('worker3', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('favor', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('airship_power', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('collection_score', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('energy_score', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('energy_cost', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('base_crafting_time', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('uid', name='item_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('marketstats',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('quality', postgresql.ENUM('legendary', 'epic', 'uncommon', 'flawless',
                                                         'common', name='itemquality'), autoincrement=False, nullable=True),
                    sa.Column('gold_price', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('gold_qty', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('gems_price', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('gems_qty', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('received_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['item.uid'], name='marketstats_item_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='marketstats_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketstats')
    op.drop_table('item')
    # ### end Alembic commands ###
